id: e38967b3e8c5437fb586635f0eb776fd
initial_creation_type: ocr
source_metadata:
  volumes:
    36015dc2b54746959634dab8966cae44:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: རྡོ་རྗེ་སེམས་དཔའི་སྒྲུབ་ཐབས།
      total_pages: 1634
      volume_number: 18
